// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/social/social.proto

package social_service // import "rpc/social/pb"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FollowItem struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	TargetId             int64    `protobuf:"varint,2,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
	FollowType           int32    `protobuf:"varint,3,opt,name=follow_type,json=followType" json:"follow_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowItem) Reset()         { *m = FollowItem{} }
func (m *FollowItem) String() string { return proto.CompactTextString(m) }
func (*FollowItem) ProtoMessage()    {}
func (*FollowItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_6f0a2fe2d7e7fb81, []int{0}
}
func (m *FollowItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowItem.Unmarshal(m, b)
}
func (m *FollowItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowItem.Marshal(b, m, deterministic)
}
func (dst *FollowItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowItem.Merge(dst, src)
}
func (m *FollowItem) XXX_Size() int {
	return xxx_messageInfo_FollowItem.Size(m)
}
func (m *FollowItem) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowItem.DiscardUnknown(m)
}

var xxx_messageInfo_FollowItem proto.InternalMessageInfo

func (m *FollowItem) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *FollowItem) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *FollowItem) GetFollowType() int32 {
	if m != nil {
		return m.FollowType
	}
	return 0
}

type FollowRequest struct {
	FollowItem           *FollowItem `protobuf:"bytes,1,opt,name=follow_item,json=followItem" json:"follow_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FollowRequest) Reset()         { *m = FollowRequest{} }
func (m *FollowRequest) String() string { return proto.CompactTextString(m) }
func (*FollowRequest) ProtoMessage()    {}
func (*FollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_6f0a2fe2d7e7fb81, []int{1}
}
func (m *FollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowRequest.Unmarshal(m, b)
}
func (m *FollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowRequest.Marshal(b, m, deterministic)
}
func (dst *FollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowRequest.Merge(dst, src)
}
func (m *FollowRequest) XXX_Size() int {
	return xxx_messageInfo_FollowRequest.Size(m)
}
func (m *FollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowRequest proto.InternalMessageInfo

func (m *FollowRequest) GetFollowItem() *FollowItem {
	if m != nil {
		return m.FollowItem
	}
	return nil
}

type EmptyResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyResponse) Reset()         { *m = EmptyResponse{} }
func (m *EmptyResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyResponse) ProtoMessage()    {}
func (*EmptyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_6f0a2fe2d7e7fb81, []int{2}
}
func (m *EmptyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyResponse.Unmarshal(m, b)
}
func (m *EmptyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyResponse.Marshal(b, m, deterministic)
}
func (dst *EmptyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyResponse.Merge(dst, src)
}
func (m *EmptyResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyResponse.Size(m)
}
func (m *EmptyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyResponse proto.InternalMessageInfo

type UnfollowRequest struct {
	FollowItem           *FollowItem `protobuf:"bytes,1,opt,name=follow_item,json=followItem" json:"follow_item,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UnfollowRequest) Reset()         { *m = UnfollowRequest{} }
func (m *UnfollowRequest) String() string { return proto.CompactTextString(m) }
func (*UnfollowRequest) ProtoMessage()    {}
func (*UnfollowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_6f0a2fe2d7e7fb81, []int{3}
}
func (m *UnfollowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnfollowRequest.Unmarshal(m, b)
}
func (m *UnfollowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnfollowRequest.Marshal(b, m, deterministic)
}
func (dst *UnfollowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnfollowRequest.Merge(dst, src)
}
func (m *UnfollowRequest) XXX_Size() int {
	return xxx_messageInfo_UnfollowRequest.Size(m)
}
func (m *UnfollowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnfollowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnfollowRequest proto.InternalMessageInfo

func (m *UnfollowRequest) GetFollowItem() *FollowItem {
	if m != nil {
		return m.FollowItem
	}
	return nil
}

type ListRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	LastId               int64    `protobuf:"varint,2,opt,name=last_id,json=lastId" json:"last_id,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
	FollowType           int32    `protobuf:"varint,4,opt,name=follow_type,json=followType" json:"follow_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_6f0a2fe2d7e7fb81, []int{4}
}
func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (dst *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(dst, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

func (m *ListRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ListRequest) GetLastId() int64 {
	if m != nil {
		return m.LastId
	}
	return 0
}

func (m *ListRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListRequest) GetFollowType() int32 {
	if m != nil {
		return m.FollowType
	}
	return 0
}

type ListResponse struct {
	Uids                 []int64  `protobuf:"varint,1,rep,packed,name=uids" json:"uids,omitempty"`
	HasMore              bool     `protobuf:"varint,2,opt,name=has_more,json=hasMore" json:"has_more,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_6f0a2fe2d7e7fb81, []int{5}
}
func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (dst *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(dst, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetUids() []int64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

func (m *ListResponse) GetHasMore() bool {
	if m != nil {
		return m.HasMore
	}
	return false
}

type CountRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	FollowType           int32    `protobuf:"varint,2,opt,name=follow_type,json=followType" json:"follow_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountRequest) Reset()         { *m = CountRequest{} }
func (m *CountRequest) String() string { return proto.CompactTextString(m) }
func (*CountRequest) ProtoMessage()    {}
func (*CountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_6f0a2fe2d7e7fb81, []int{6}
}
func (m *CountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountRequest.Unmarshal(m, b)
}
func (m *CountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountRequest.Marshal(b, m, deterministic)
}
func (dst *CountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountRequest.Merge(dst, src)
}
func (m *CountRequest) XXX_Size() int {
	return xxx_messageInfo_CountRequest.Size(m)
}
func (m *CountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CountRequest proto.InternalMessageInfo

func (m *CountRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CountRequest) GetFollowType() int32 {
	if m != nil {
		return m.FollowType
	}
	return 0
}

type CountResponse struct {
	FollowCount          int64    `protobuf:"varint,1,opt,name=follow_count,json=followCount" json:"follow_count,omitempty"`
	FollowerCount        int64    `protobuf:"varint,2,opt,name=follower_count,json=followerCount" json:"follower_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountResponse) Reset()         { *m = CountResponse{} }
func (m *CountResponse) String() string { return proto.CompactTextString(m) }
func (*CountResponse) ProtoMessage()    {}
func (*CountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_6f0a2fe2d7e7fb81, []int{7}
}
func (m *CountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountResponse.Unmarshal(m, b)
}
func (m *CountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountResponse.Marshal(b, m, deterministic)
}
func (dst *CountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountResponse.Merge(dst, src)
}
func (m *CountResponse) XXX_Size() int {
	return xxx_messageInfo_CountResponse.Size(m)
}
func (m *CountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CountResponse proto.InternalMessageInfo

func (m *CountResponse) GetFollowCount() int64 {
	if m != nil {
		return m.FollowCount
	}
	return 0
}

func (m *CountResponse) GetFollowerCount() int64 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

type FollowAllRequest struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowAllRequest) Reset()         { *m = FollowAllRequest{} }
func (m *FollowAllRequest) String() string { return proto.CompactTextString(m) }
func (*FollowAllRequest) ProtoMessage()    {}
func (*FollowAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_6f0a2fe2d7e7fb81, []int{8}
}
func (m *FollowAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowAllRequest.Unmarshal(m, b)
}
func (m *FollowAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowAllRequest.Marshal(b, m, deterministic)
}
func (dst *FollowAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowAllRequest.Merge(dst, src)
}
func (m *FollowAllRequest) XXX_Size() int {
	return xxx_messageInfo_FollowAllRequest.Size(m)
}
func (m *FollowAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FollowAllRequest proto.InternalMessageInfo

func (m *FollowAllRequest) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type FollowAllResponse struct {
	Uids                 []int64  `protobuf:"varint,2,rep,packed,name=uids" json:"uids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FollowAllResponse) Reset()         { *m = FollowAllResponse{} }
func (m *FollowAllResponse) String() string { return proto.CompactTextString(m) }
func (*FollowAllResponse) ProtoMessage()    {}
func (*FollowAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_social_6f0a2fe2d7e7fb81, []int{9}
}
func (m *FollowAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FollowAllResponse.Unmarshal(m, b)
}
func (m *FollowAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FollowAllResponse.Marshal(b, m, deterministic)
}
func (dst *FollowAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FollowAllResponse.Merge(dst, src)
}
func (m *FollowAllResponse) XXX_Size() int {
	return xxx_messageInfo_FollowAllResponse.Size(m)
}
func (m *FollowAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FollowAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FollowAllResponse proto.InternalMessageInfo

func (m *FollowAllResponse) GetUids() []int64 {
	if m != nil {
		return m.Uids
	}
	return nil
}

func init() {
	proto.RegisterType((*FollowItem)(nil), "social.FollowItem")
	proto.RegisterType((*FollowRequest)(nil), "social.FollowRequest")
	proto.RegisterType((*EmptyResponse)(nil), "social.EmptyResponse")
	proto.RegisterType((*UnfollowRequest)(nil), "social.UnfollowRequest")
	proto.RegisterType((*ListRequest)(nil), "social.ListRequest")
	proto.RegisterType((*ListResponse)(nil), "social.ListResponse")
	proto.RegisterType((*CountRequest)(nil), "social.CountRequest")
	proto.RegisterType((*CountResponse)(nil), "social.CountResponse")
	proto.RegisterType((*FollowAllRequest)(nil), "social.FollowAllRequest")
	proto.RegisterType((*FollowAllResponse)(nil), "social.FollowAllResponse")
}

func init() { proto.RegisterFile("proto/social/social.proto", fileDescriptor_social_6f0a2fe2d7e7fb81) }

var fileDescriptor_social_6f0a2fe2d7e7fb81 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x95, 0xe3, 0xe2, 0xa6, 0x13, 0xa7, 0x2d, 0xc3, 0x97, 0x13, 0x10, 0x04, 0x0b, 0x44, 0x4e,
	0x05, 0xb5, 0x52, 0x85, 0x84, 0x7a, 0x08, 0xd0, 0x56, 0x91, 0xe0, 0xe2, 0xc2, 0x01, 0x84, 0x14,
	0xb9, 0xf1, 0x84, 0x5a, 0xda, 0x64, 0xdd, 0xdd, 0x4d, 0x51, 0x7e, 0x1e, 0xff, 0x0c, 0x65, 0x77,
	0xfd, 0x95, 0x00, 0x52, 0xe0, 0x94, 0x99, 0x97, 0x79, 0x6f, 0xde, 0xcc, 0xac, 0x0c, 0x9d, 0x4c,
	0x70, 0xc5, 0x5f, 0x4a, 0x3e, 0x4e, 0x63, 0x66, 0x7f, 0x0e, 0x34, 0x86, 0x9e, 0xc9, 0xc2, 0x6f,
	0x00, 0x67, 0x9c, 0x31, 0xfe, 0x63, 0xa8, 0x68, 0x8a, 0xfb, 0xe0, 0xce, 0xd3, 0x24, 0x70, 0x7a,
	0x4e, 0xdf, 0x8d, 0x96, 0x21, 0x3e, 0x84, 0x1d, 0x15, 0x8b, 0xef, 0xa4, 0x46, 0x69, 0x12, 0x34,
	0x34, 0xde, 0x34, 0xc0, 0x30, 0xc1, 0x27, 0xd0, 0x9a, 0x68, 0xf2, 0x48, 0x2d, 0x32, 0x0a, 0xdc,
	0x9e, 0xd3, 0xbf, 0x15, 0x81, 0x81, 0x3e, 0x2d, 0x32, 0x0a, 0xdf, 0x43, 0xdb, 0xa8, 0x47, 0x74,
	0x3d, 0x27, 0xa9, 0xf0, 0xa8, 0x60, 0xa4, 0x8a, 0xa6, 0xba, 0x51, 0xeb, 0x10, 0x0f, 0xac, 0xb5,
	0xd2, 0x49, 0xae, 0xb2, 0x8c, 0xc3, 0x3d, 0x68, 0x9f, 0x4e, 0x33, 0xb5, 0x88, 0x48, 0x66, 0x7c,
	0x26, 0x29, 0x3c, 0x83, 0xbd, 0xcf, 0xb3, 0xc9, 0xff, 0x0b, 0x5f, 0x43, 0xeb, 0x43, 0x2a, 0x55,
	0xae, 0xb1, 0x3e, 0xfd, 0x03, 0xd8, 0x66, 0xb1, 0xac, 0xcc, 0xee, 0x2d, 0xd3, 0x61, 0x82, 0xf7,
	0xc1, 0xe3, 0x93, 0x89, 0x24, 0xa5, 0x87, 0x76, 0x23, 0x9b, 0xad, 0x6e, 0x64, 0x6b, 0x6d, 0x23,
	0x27, 0xe0, 0x9b, 0x96, 0x66, 0x14, 0x44, 0xd8, 0x9a, 0xa7, 0x89, 0x0c, 0x9c, 0x9e, 0xdb, 0x77,
	0x23, 0x1d, 0x63, 0x07, 0x9a, 0x57, 0xb1, 0x1c, 0x4d, 0xb9, 0x20, 0xdd, 0xb6, 0x19, 0x6d, 0x5f,
	0xc5, 0xf2, 0x23, 0x17, 0x14, 0x0e, 0xc0, 0x7f, 0xc7, 0xe7, 0xb3, 0xbf, 0x58, 0x5e, 0x71, 0xd0,
	0x58, 0x73, 0xf0, 0x05, 0xda, 0x56, 0xc2, 0x5a, 0x78, 0x0a, 0xbe, 0x65, 0x8c, 0x97, 0xb8, 0x15,
	0xb3, 0x2a, 0xba, 0x14, 0x9f, 0xc3, 0xae, 0x49, 0x49, 0xd8, 0x22, 0xb3, 0x8e, 0x76, 0x8e, 0xea,
	0xb2, 0xf0, 0x19, 0xec, 0x9b, 0x4d, 0x0f, 0x18, 0xfb, 0xa3, 0xc3, 0xf0, 0x05, 0xdc, 0xae, 0x54,
	0xad, 0xec, 0xa1, 0x51, 0xee, 0xe1, 0xf0, 0xa7, 0x0b, 0xfe, 0x85, 0x3e, 0xe0, 0x05, 0x89, 0x1b,
	0x12, 0x78, 0x0c, 0x9e, 0x61, 0xe2, 0xbd, 0xfa, 0x65, 0x6d, 0xb3, 0x6e, 0x01, 0xd7, 0xde, 0x0b,
	0xbe, 0x86, 0x66, 0xfe, 0x5e, 0x36, 0x64, 0x1e, 0xc3, 0xce, 0x39, 0x29, 0xdb, 0xf4, 0x4e, 0x5e,
	0x53, 0x79, 0x34, 0xdd, 0xbb, 0x75, 0xb0, 0xe8, 0xd8, 0x2a, 0x78, 0x24, 0x36, 0x61, 0x9e, 0xc0,
	0x6e, 0xc1, 0x34, 0xcb, 0x2f, 0xea, 0xaa, 0x97, 0x2f, 0x0d, 0xd7, 0x8f, 0x79, 0x0a, 0x7e, 0x41,
	0x1f, 0x30, 0x86, 0x41, 0x7d, 0xdc, 0xf2, 0x30, 0xdd, 0xce, 0x6f, 0xfe, 0x31, 0x22, 0xaf, 0x1c,
	0x3c, 0xaf, 0xb8, 0x20, 0xf1, 0xef, 0x42, 0x6f, 0x1f, 0x7f, 0x7d, 0x24, 0xb2, 0x71, 0xfe, 0x09,
	0xca, 0x2e, 0xdf, 0x98, 0x68, 0x24, 0x49, 0xdc, 0xa4, 0x63, 0xba, 0xf4, 0xf4, 0xe7, 0xe8, 0xe8,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x49, 0x71, 0x65, 0xab, 0x04, 0x00, 0x00,
}
